In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
a = [1,2,3]
np.array(a)
# The above code will create a numpy array from a list and display it.

array([1, 2, 3])

In [13]:
np.arange(1,11)
# The above code will create a numpy array with values from 1 to 10.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:

np.arange(1,11,2)
# The above code will create a numpy array with values from 1 to 10 with a step of 2.

array([1, 3, 5, 7, 9])

In [15]:
np.zeros((3,4))
# The above code will create a 3x4 numpy array filled with zeros.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))
# The above code will create a 3x4 numpy array filled with ones.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
np.linspace(1,10,5)
# The above code will create a numpy array with 5 evenly spaced values between 1 and 10. 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [3]:
np.eye(5)
# The above code will create a 5x5 identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
np.random.rand(3,4)
# The above code will create a 3x4 numpy array with random values between 0 and 1.

array([[0.90130922, 0.54469701, 0.39737879, 0.93593505],
       [0.57100909, 0.96863685, 0.32020063, 0.80137341],
       [0.7646717 , 0.83519172, 0.10669165, 0.80728924]])

In [8]:
y = np.random.randint(1,40,20)
# The above code will create a numpy array with 5 random integers between 1 and 10.
y

array([24, 22, 14,  9,  8, 28, 25, 22,  5, 21, 31, 17, 34, 10, 17,  1, 14,
       27, 29,  3])

In [9]:
y.reshape(4,5)
# The above code will reshape the numpy array y into a 4x5 array.

array([[24, 22, 14,  9,  8],
       [28, 25, 22,  5, 21],
       [31, 17, 34, 10, 17],
       [ 1, 14, 27, 29,  3]])

In [10]:
y.max()
# The above code will return the maximum value in the numpy array y.

34

In [ ]:
y[8]
# The above code will return the value at index 8 in the numpy array y.

5

In [16]:
x = y[3:7]
x
# The above code will return the values from index 3 to 6 in the numpy array y.

array([ 9,  8, 28, 25])

In [ ]:
x[:] = 99
x
# The above code will set all values in the numpy array x to 99.

array([99, 99, 99, 99])

In [20]:
ar_2d = np.random.randint(1,40,16).reshape(4,4)
ar_2d

array([[31, 17, 21, 30],
       [18, 33, 23, 29],
       [ 9,  1,  6,  3],
       [38, 25, 33, 17]])

In [ ]:
arr = ar_2d > 20
arr
# The above code will create a boolean array where each element is True if the corresponding element in ar_2d is greater than 20, and False otherwise.

array([[ True, False,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True, False]])

In [ ]:
ar_2d[1][1]
# The above code will return the value at row 1, column 1 in the 2D numpy array ar_2d.

33

In [ ]:
ar_2d[:2,1:]
# The above code will return the values from row 0 to 1 and column 1 to 3 in the 2D numpy array ar_2d.

array([[17, 21, 30],
       [33, 23, 29]])

In [28]:
ar_2d_1 = np.random.randint(1,20,16).reshape(4,4)
ar_2d_1

array([[18,  9,  9, 17],
       [10, 19, 14,  9],
       [11,  4,  1, 17],
       [13, 13, 19,  9]])

In [ ]:
ar_2d + ar_2d_1
# The above code will add the two 2D numpy arrays ar_2d and ar_2d_1 element-wise.

array([[49, 26, 30, 47],
       [28, 52, 37, 38],
       [20,  5,  7, 20],
       [51, 38, 52, 26]])

In [32]:
ar_2d * ar_2d_1

array([[558, 153, 189, 510],
       [180, 627, 322, 261],
       [ 99,   4,   6,  51],
       [494, 325, 627, 153]])

In [33]:
np.sqrt(ar_2d)
# The above code will return the square root of each element in the 2D numpy array ar_2d.

array([[5.56776436, 4.12310563, 4.58257569, 5.47722558],
       [4.24264069, 5.74456265, 4.79583152, 5.38516481],
       [3.        , 1.        , 2.44948974, 1.73205081],
       [6.164414  , 5.        , 5.74456265, 4.12310563]])